apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup-keycloak
spec:
  schedule: "0 23 * * *"

  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Replace

  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: postgres-azure-backup
              image: helfenkannjedercontainer.azurecr.io/backup.postgres
              imagePullPolicy: IfNotPresent

              resources:
                limits:
                  cpu: 200m
                  memory: 200Mi
                requests:
                  cpu: 50m
                  memory: 50Mi

              env:
                - name: PGHOST
                  valueFrom:
                    configMapKeyRef:
                      name: azure-backup-config
                      key: azure.backup.keycloak.host
                - name: PGPORT
                  valueFrom:
                    configMapKeyRef:
                      name: azure-backup-config
                      key: azure.backup.keycloak.port
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: keycloak-db-secret
                      key: keycloak.postgres.user
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: keycloak-db-secret
                      key: keycloak.postgres.password
                - name: PGDATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: keycloak-db-config
                      key: keycloak.postgres.db
                - name: AZCOPY_DESTINATION_URL
                  valueFrom:
                    configMapKeyRef:
                      name: azure-backup-config
                      key: azure.backup.destination.url
                - name: AZCOPY_SAS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: azure-backup-secret
                      key: azure.backup.sas.token
          restartPolicy: Never
